(test) O3-2514 : Setup the template repository with playwright
openmrs/openmrs-esm-template-app pull request #18
Opened 2023-11-18 11:31 UTC by RandilaP

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
The goal of this PR is to set up the esm template repository for E2E testing with playwright

## Screenshots

## Related Issue

https://issues.openmrs.org/browse/O3-2514

## Other

2023-11-18 11:31 UTC, RandilaP commented
@jayasanka-sack Could you please review this

2023-11-23 07:15 UTC, jayasanka-sack requested changes
Thanks @RandilaP. I've added some comments. Let me know what you think.

2023-11-23 07:15 UTC, jayasanka-sack commented on e2e/specs/initiate-test.spec.ts
> +test("initiate test", async ({ page}) => {
```suggestion
test("Sample test", async ({ page}) => {
```

2023-11-23 07:15 UTC, jayasanka-sack commented on e2e/specs/initiate-test.spec.ts
> +});
Add a newline at the end of the file

2023-11-23 07:15 UTC, jayasanka-sack commented on e2e/README.md
> +about to change in the future. Stay tuned for updates!
Add the `.env.example` file to the root. Also update the root readme file with instructions to copy the `.env.example` file and create `.env` file by running `cp .env.example .env`). Link to this readme file too.

2023-11-23 07:15 UTC, jayasanka-sack commented on e2e/README.md
> +This is very much underdeveloped/WIP. At the moment, there exists a (git-shared) `.env`
```suggestion
This is very much underdeveloped/WIP. At the moment, there exists a (git-shared) `.env.example`
```

2023-11-23 07:18 UTC, jayasanka-sack commented
Also, update the jest config file to skip playwright test files (that's why the build is failing). 

`testPathIgnorePatterns: [path.resolve(__dirname, 'e2e')],`
`collectCoverageFrom....`

2023-12-10 10:22 UTC, RandilaP commented
@jayasanka-sack Could you please review this

2023-12-21 06:27 UTC, jayasanka-sack commented
@RandilaP the build is still failing. could you please check?

2024-01-18 04:55 UTC, RandilaP commented
@jayasanka-sack Could you please approve the workflow

2024-01-18 08:28 UTC, jayasanka-sack approved these changes
Thanks @RandilaP !

2024-01-18 08:28 UTC, merged